CREATE TABLE CATEGORIES (
  CATEGORYID D_ID,
  CATEGORYNAME D_NAME
);

INSERT INTO "CATEGORIES" VALUES (1, 'Elektronika');
INSERT INTO "CATEGORIES" VALUES (2, 'Książki');
INSERT INTO "CATEGORIES" VALUES (3, 'Ogród');
