CREATE TABLE EMPLOYEES (
  EMPLOYEEID D_ID,
  FIRSTNAME VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
  LASTNAME VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
  HIREDATE D_HIRE_DATE,
  NOTES D_DESCRIPTION,
  SALARY D_PRICE,
  PHOTO BLOB SUB_TYPE BINARY
);

INSERT INTO "EMPLOYEES" VALUES (1, 'Jan', 'Kowalski', '2020-03-01', 'Doświadczony programista. Specjalista od Firebird.', 15000, NULL);
INSERT INTO "EMPLOYEES" VALUES (2, 'Anna', 'Nowak', '2022-08-15', NULL, 9500.5, NULL);
