SET TERM ^ ;
CREATE PROCEDURE GET_EMPLOYEE_DETAILS (EMP_ID INTEGER) RETURNS (FULL_NAME VARCHAR(102), HIRE_DATE_INFO VARCHAR(50), SALARY_INFO VARCHAR(50)) AS
DECLARE VARIABLE FN VARCHAR(50);
    DECLARE VARIABLE LN VARCHAR(50);
    DECLARE VARIABLE HD D_HIRE_DATE;
    DECLARE VARIABLE SAL D_PRICE;
BEGIN
   FOR SELECT FirstName, LastName, HireDate, Salary
        FROM EMPLOYEES
        WHERE EmployeeID = :EMP_ID
        INTO :FN, :LN, :HD, :SAL
    DO
    BEGIN
        FULL_NAME = LN || ', ' || FN;
        HIRE_DATE_INFO = 'Zatrudniony od: ' || HD;
        SALARY_INFO = 'Pensja: ' || SAL || ' PLN';
        SUSPEND;
    END
END
^
SET TERM ; ^
